version: "3"

services:
  fastapi:
    build: backend/
    # volumes:
    #   - backend:/app/backend
    volumes:
      - backend:/app/backend
    ports:
      - "5000:5000"
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit

  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
    volumes:
      # - './backend/sql_app.db:/app/data.db'
      - backend:/app/backend
      - './grafana_config/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana_config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml'
      - './grafana_config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml'
      # - './grafana_config/dashboards/alert.json:/app/dashboards/alert.json'
      - './grafana_config/dashboards/graph_and_variables.json:/app/dashboards/graph_and_variables.json'
      # - './grafana_config/dashboards/query_and_repitition.json:/app/dashboards/query_and_repitition.json'
    ports:
      - 3000:3000
    container_name: grafana
    depends_on:
      - streamlit

volumes:
  backend:

networks:
  deploy_network:
    driver: bridge
