{
 "title": "Prediction App Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Predictions",
   "type": "barchart",
   "description": "0 -> Very Cheap\n1 -> Cheap\n2 -> Expensive\n3 -> Very Expensive",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT prediction, datetime FROM predictions;",
     "rawQueryText": "SELECT prediction, datetime FROM predictions;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Prediction Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(prediction) FROM predictions;",
     "rawQueryText": "SELECT count(prediction) FROM predictions;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Detailed Predictions Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "queryText": "SELECT id, prediction, datetime FROM predictions;\n",
     "rawQueryText": "SELECT id, prediction, datetime FROM predictions;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}